# Generated by Django 4.1.7 on 2023-06-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0007_product_price_usd"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="status",
            field=models.CharField(
                choices=[
                    ("IN_CART", "В корзине"),
                    ("PAID", "Оплачено"),
                    ("DELIVERED", "Отправлено"),
                ],
                default="IN_CART",
                max_length=32,
            ),
        ),
    ]
